spring:
  profiles:
    active: dev
  application:
    name: cemp-api
server:
  port: 30000
  servlet:
    context-path: /
  #如果是微服务环境,所有请求需要通过网关转发和返回时,则以下配置需要配置在网关上,而不是目标微服务上
  compression:
    #是否对响应数据开启gzip压缩,默认false
    enabled: true
    #响应内容长度超过设置大小时进行压缩,默认值为2048(2KB,不带单位时默认为字节)
    min-response-size: 10KB
    #对指定的响应类型进行压缩,值是数组,用逗号隔开
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

nacos:
  logging:
    default:
      config:
        enabled: false
