spring:
  cloud:
    nacos:
      config:
        server-addr: 172.20.1.92:18848
        namespace: 15e81f88-21a3-4d3f-923d-f5d7a5bad798
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        server-addr: 172.20.1.92:18848
        namespace: 15e81f88-21a3-4d3f-923d-f5d7a5bad798
        group: DEFAULT_GROUP
      username: nacos
      password: landleaf@123.com
  config:
    import:
      - optional:nacos:${spring.application.name}
      - optional:nacos:license