version: "3.5"
services:
  cemp-gateway:
    container_name: cemp-gateway
    image: cemp-gateway-test:latest
    build:
      context: ./cemp-gateway
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-oauth:
    container_name: cemp-oauth
    image: cemp-oauth-test:latest
    build:
      context: ./cemp-oauth
      dockerfile: dockerfile
    ports:
      - "30001:30001"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-bms:
    container_name: cemp-bms
    image: cemp-bms-test:latest
    build:
      context: ./cemp-bms
      dockerfile: dockerfile
    ports:
      - "30002:30002"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-file:
    container_name: cemp-file
    image: cemp-file-test:latest
    build:
      context: ./cemp-file
      dockerfile: dockerfile
    ports:
      - "30003:30003"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-lgc:
    container_name: cemp-lgc
    image: cemp-lgc-test:latest
    build:
      context: ./cemp-lgc
      dockerfile: dockerfile
    ports:
      - "30004:30004"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-monitor:
    container_name: cemp-monitor
    image: cemp-monitor-test:latest
    build:
      context: ./cemp-monitor
      dockerfile: dockerfile
    ports:
      - "30010:30010"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-data:
    container_name: cemp-data
    image: cemp-data-test:latest
    build:
      context: ./cemp-data
      dockerfile: dockerfile
    ports:
      - "30020:30020"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-energy:
    container_name: cemp-energy
    image: cemp-energy-test:latest
    build:
      context: ./cemp-energy
      dockerfile: dockerfile
    ports:
      - "30030:30030"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-job:
    container_name: cemp-job
    image: cemp-job-test:latest
    build:
      context: ./cemp-job
      dockerfile: dockerfile
    ports:
      - "30040:30040"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  ## gateway-锦江
  cemp-gw-jinjiang:
    container_name: cemp-gw-jinjiang
    image: cemp-gw-jinjiang-test:latest
    build:
      context: ./cemp-gw-jinjiang
      dockerfile: dockerfile
    ports:
      - "20000:20000"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-gw-lgc:
    container_name: cemp-gw-lgc
    image: cemp-gw-lgc-test:latest
    build:
      context: ./cemp-gw-lgc
      dockerfile: dockerfile
    ports:
      - "20001:20001"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-gateway-lgc:
    container_name: cemp-gateway-lgc
    image: cemp-gw-test:latest
    build:
      context: ./cemp-gw
      dockerfile: ./lgc/dockerfile
    ports:
      - "20002:20002"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-gateway-jingjiang:
    container_name: cemp-gateway-jingjiang
    image: cemp-gw-test:latest
    build:
      context: ./cemp-gw
      dockerfile: ./jingjiang/dockerfile
    ports:
      - "20003:20003"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-cus-jjgj:
    container_name: cemp-cus-jjgj
    image: cemp-cus-jjgj-test:latest
    build:
      context: ./cemp-cus-jjgj
      dockerfile: dockerfile
    ports:
      - "31001:31001"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-messaging:
    container_name: cemp-messaging
    image: cemp-messaging-test:latest
    build:
      context: ./cemp-messaging
      dockerfile: dockerfile
    ports:
      - "25000:25000"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.93
  cemp-engine:
    container_name: cemp-engine
    image: cemp-engine:lastest
    build:
      context: ./cemp-engine
      dockerfile: dockerfile
    ports:
      - "30060:30060"
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.95