version: "3.5"
services:
  cemp-gateway:
    container_name: cemp-gateway
    image: cemp-gateway-dev:latest
    restart: always
    build:
      context: ./cemp-gateway
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-oauth:
    container_name: cemp-oauth
    image: cemp-oauth-dev:latest
    restart: always
    build:
      context: ./cemp-oauth
      dockerfile: dockerfile
    ports:
      - "30001:30001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-bms:
    container_name: cemp-bms
    image: cemp-bms-dev:latest
    restart: always
    build:
      context: ./cemp-bms
      dockerfile: dockerfile
    ports:
      - "30002:30002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-file:
    container_name: cemp-file
    image: cemp-file-dev:latest
    restart: always
    build:
      context: ./cemp-file
      dockerfile: dockerfile
    ports:
      - "30003:30003"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-lgc:
    container_name: cemp-lgc
    image: cemp-lgc-dev:latest
    restart: always
    build:
      context: ./cemp-lgc
      dockerfile: dockerfile
    ports:
      - "30004:30004"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-monitor:
    container_name: cemp-monitor
    image: cemp-monitor-dev:latest
    restart: always
    build:
      context: ./cemp-monitor
      dockerfile: dockerfile
    ports:
      - "30010:30010"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-data:
    container_name: cemp-data
    image: cemp-data-dev:latest
    restart: always
    build:
      context: ./cemp-data
      dockerfile: dockerfile
    ports:
      - "30020:30020"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-energy:
    container_name: cemp-energy
    image: cemp-energy-dev:latest
    restart: always
    build:
      context: ./cemp-energy
      dockerfile: dockerfile
    ports:
      - "30030:30030"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-job:
    container_name: cemp-job
    image: cemp-job-dev:latest
    restart: always
    build:
      context: ./cemp-job
      dockerfile: dockerfile
    ports:
      - "30040:30040"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-gw-jinjiang:
    container_name: cemp-gw-jinjiang
    image: cemp-gw-jinjiang-dev:latest
    restart: always
    build:
      context: ./cemp-gw-jinjiang
      dockerfile: dockerfile
    ports:
      - "20000:20000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-gw-lgc:
    container_name: cemp-gw-lgc
    image: cemp-gw-lgc-dev:latest
    restart: always
    build:
      context: ./cemp-gw-lgc
      dockerfile: dockerfile
    ports:
      - "20001:20001"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-gateway-lgc:
    container_name: cemp-gateway-lgc
    image: cemp-gw-dev:latest
    restart: always
    build:
      context: ./cemp-gw
      dockerfile: ./lgc/dockerfile
    ports:
      - "20002:20002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-gateway-jingjiang:
    container_name: cemp-gateway-jingjiang
    image: cemp-gw-dev:latest
    restart: always
    build:
      context: ./cemp-gw
      dockerfile: ./jingjiang/dockerfile
    ports:
      - "20003:20003"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-gateway-jzd:
    container_name: cemp-gateway-jzd
    image: cemp-gateway-jzd-dev:latest
    restart: always
    build:
      context: ./cemp-gw-jzd
      dockerfile: dockerfile
    ports:
      - "20004:20004"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-cus-jjgj:
    container_name: cemp-cus-jjgj
    image: cemp-cus-jjgj-dev:latest
    restart: always
    build:
      context: ./cemp-cus-jjgj
      dockerfile: dockerfile
    ports:
      - "31001:31001"
  cemp-cus-sdl:
    container_name: cemp-cus-sdl
    image: cemp-cus-sdl-dev:latest
    restart: always
    build:
      context: ./cemp-cus-sdl
      dockerfile: dockerfile
    ports:
      - "31002:31002"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-cus-jzd:
    container_name: cemp-cus-jzd
    image: cemp-cus-jzd:latest
    restart: always
    build:
      context: ./cemp-cus-jzd
      dockerfile: dockerfile
    ports:
      - "31003:31003"
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-cus-lh:
    container_name: cemp-cus-lh
    image: cemp-cus-lh:latest
    restart: always
    build:
      context: ./cemp-cus-lh
      dockerfile: dockerfile
    ports:
      - "31004:31004"
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-messaging:
    container_name: cemp-messaging
    image: cemp-messaging-dev:latest
    restart: always
    build:
      context: ./cemp-messaging
      dockerfile: dockerfile
    ports:
      - "25000:25000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.94
  cemp-engine:
    container_name: cemp-engine
    image: cemp-engine:lastest
    build:
      context: ./cemp-engine
      dockerfile: dockerfile
    ports:
      - "30060:30060"
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.20.1.95