spring:
  cloud:
    nacos:
      username: nacos
      password: landleaf@123.com
      server-addr: 172.20.1.92:18848
      discovery:
        namespace: 85a45da8-c86e-4d76-b41d-e83b6b5cd154
        group: DEFAULT_GROUP
      config:
        server-addr: 172.20.1.92:18848
        namespace: 85a45da8-c86e-4d76-b41d-e83b6b5cd154
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - optional:nacos:${spring.application.name}
      - optional:nacos:license