spring:
  cloud:
    nacos:
      config:
        server-addr: 172.20.1.92:18848
        namespace: 69cce1db-12ee-4205-9e02-041f3b05aa3c
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        ip: 172.20.1.94
        server-addr: 172.20.1.92:18848
        namespace: 69cce1db-12ee-4205-9e02-041f3b05aa3c
        group: DEFAULT_GROUP
      username: nacos
      password: landleaf@123.com
  config:
    import:
      - optional:nacos:${spring.application.name}
      - optional:nacos:license