spring:
  profiles:
    active: dev
  application:
    name: cemp-gw-jinjiang
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务
server:
  port: 20000
  servlet:
    context-path: /
  #如果是微服务环境,所有请求需要通过网关转发和返回时,则以下配置需要配置在网关上,而不是目标微服务上
  compression:
    #是否对响应数据开启gzip压缩,默认false
    enabled: true
    #响应内容长度超过设置大小时进行压缩,默认值为2048(2KB,不带单位时默认为字节)
    min-response-size: 10KB
    #对指定的响应类型进行压缩,值是数组,用逗号隔开
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml

nacos:
  logging:
    default:
      config:
        enabled: false

# knife4j
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.landleaf.gw.controller
  default-flat-param-object: false